Repository 42-seconds-to-Epita/Raiders-Tactics, pull requests merged in 2023-01, with the labels that each got.

#3 Mirror start
  Assets/.idea/.idea.Assets.dir/.idea/.gitignore
  Assets/.idea/.idea.Assets.dir/.idea/encodings.xml
  Assets/.idea/.idea.Assets.dir/.idea/indexLayout.xml
  Assets/.idea/.idea.Assets.dir/.idea/vcs.xml
  Assets/Player.prefab
  Assets/Player.prefab.meta
  Assets/Scenes/Main.unity
  Assets/Scenes/Main.unity.meta
  Assets/Scripts.meta
  Assets/Scripts/.idea/.idea.Scripts.dir/.idea/indexLayout.xml
  Assets/Scripts/.idea/.idea.Scripts.dir/.idea/projectSettingsUpdater.xml
  Assets/Scripts/.idea/.idea.Scripts.dir/.idea/workspace.xml
  Assets/Scripts/PlayerScript.cs
  Assets/Scripts/PlayerScript.cs.meta
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/SceneTemplateSettings.json
  ProjectSettings/TimelineSettings.asset
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2021.dwlt
Labels: enhancement, multiplayer

#6 [Camera] Fix files
  Assets/Scenes/Main.unity
  UserSettings/Layouts/default-2021.dwlt
Labels: bug, multiplayer

#7 feat: added GPL 3.0 to the project
  LICENSE
Labels: documentation, enhancement

#9 Prevent Git merge conflicts
  .gitattributes
  .gitignore
  ProjectSettings/ProjectSettings.asset
Labels: bug, enhancement, urgent
